// Code generated by cmd/codegen from https://github.com/saveme712/cimgui-go.
// DO NOT EDIT.


#pragma once

#include "../cwrappers/cimmarkdown.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif